import React from "react";
import styles from "./Content.module.scss"

const Content = (props) => {
    return (
        <div className={styles.content}>
            <div className={styles.text}>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                </p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                </p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                </p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia tempore magnam perferendis eius, laudantium quos ducimus molestias. Voluptate cum cumque exercitationem iure esse quasi reprehenderit culpa quaerat, necessitatibus quae architecto.
                </p>
            </div>
        </div>
    )
}


export default Content